name: hello-world
on: push
jobs:
  my-job1:
    runs-on: ubuntu-latest
    steps:
      - name: my-step1
        run: echo "Hello World!"
  my-job2:
    runs-on: ubuntu-latest
    steps:
      - name: my-step2
        run: echo "Hello VIJAY! HW R U? !!"
